/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Yisin' at '16-10-18 下午10:07' with Gradle 3.1
 *
 * @author Yisin, @date 16-10-18 下午10:07
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
